# -*- coding: utf-8 -*-
"""Mlops project 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xWxKyW_8g_CA4qnbePy_d7ky3N37NOc
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/sample_data/Titanic-Dataset.csv")

df.head()

df.isnull().sum()

df.drop(columns=['Age', 'Cabin'])

df.isnull().sum()

df = df.drop(columns=['Cabin'], errors='ignore')
df = df.dropna()
df.isnull().sum()

df.isnull().sum()

df.columns

df["Age"].isna().sum()

df["Age"].mean()

np.round(df["Age"].mean())

df["Age"].fillna(np.round(df['Age'].mean()))

df['Age'] = df['Age'].fillna(np.round(df['Age'].mean()))

df['Age'].isna().sum()

df["Age"] = df["Age"].fillna(  np.round(df["Age"].mean())  )

df.dropna(inplace=True)

df

df.dtypes

df=pd.get_dummies(df,drop_first=True)

df

df

df=pd.get_dummies(df,drop_first=True)

df

df.drop("Survived",axis=1)

df

X=df.drop("Survived",axis=1)

X

y=df["Survived"]

y

X

y

X.shape

y.shape

from sklearn.model_selection import train_test_split

from numpy.matrixlib import test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=2)

X.shape,X_train.shape,X_test.shape

y.shape,y_train.shape,y_test.shape

from  xgboost import XGBClassifier

xgb_model = XGBClassifier()

xgb_model

xgb_model.fit(X_train, y_train)
xgb_model.score(X_train, y_train)

import pickle
from google.colab import files

# Save the trained model
with open('xgb_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)

# Download the file to your computer
files.download('xgb_model.pkl')